version: '3.9'

services:

  postgres_db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data-rebase-labs:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis

  rebase-labs:
    container_name: rebase-labs
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
      - ./bundle:/usr/local/bundle
    command: bash -c "bundle && ruby server.rb"
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres_db
      - redis

  sidekiq:
    container_name: sidekiq
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
      - ./bundle:/usr/local/bundle
    environment:
      REDIS_URL: redis://redis:6379/0            
    command: bash -c "bundle exec sidekiq -r /app/core/importer.rb" 
    depends_on:
      - rebase-labs
      - redis
    
  sidekiq_web:
    image: aschzero/sidekiq-web
    environment:
      REDIS_URL: redis://redis:6379
      SIDEKIQ_USER: sidekiq
      SIDEKIQ_PASSWORD: sidekiq
    ports:
      - 3030:3030
    depends_on:
      - sidekiq

  chrome:
    image: selenium/node-chrome:4.11.0-20230801
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.11.0-20230801
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"